export const driverOptions = [
  { label: "Alexander Albon", value: "ALB" },
  { label: "Fernando Alonso", value: "ALO" },
  { label: "Valtteri Bottas", value: "BOT" },
  { label: "Marcus Ericsson", value: "ERI" },
  { label: "Pietro Fittipaldi", value: "FIT" },
  { label: "Pierre Gasly", value: "GAS" },
  { label: "Antonio Giovinazzi", value: "GIO" },
  { label: "Romain Grosjean", value: "GRO" },
  { label: "Lewis Hamilton", value: "HAM" },
  { label: "Brendon Hartley", value: "HAR" },
  { label: "Nico Hülkenberg", value: "HUL" },
  { label: "Robert Kubica", value: "KUB" },
  { label: "Daniil Kvyat", value: "KVY" },
  { label: "Nicholas Latifi", value: "LAT" },
  { label: "Charles Leclerc", value: "LEC" },
  { label: "Kevin Magnussen", value: "MAG" },
  { label: "Nikita Mazepin", value: "MAZ" },
  { label: "Mick Schumacher", value: "MSC" },
  { label: "Lando Norris", value: "NOR" },
  { label: "Esteban Ocon", value: "OCO" },
  { label: "Sergio Perez", value: "PER" },
  { label: "Kimi Räikkönen", value: "RAI" },
  { label: "Daniel Ricciardo", value: "RIC" },
  { label: "George Russell", value: "RUS" },
  { label: "Carlos Sainz", value: "SAI" },
  { label: "Sergey Sirotkin", value: "SIR" },
  { label: "Lance Stroll", value: "STR" },
  { label: "Yuki Tsunoda", value: "TSU" },
  { label: "Stoffel Vandoorne", value: "VAN" },
  { label: "Max Verstappen", value: "VER" },
  { label: "Sebastian Vettel", value: "VET" },
  { label: "Guanyu Zhou", value: "ZHO" },
  { label: "Aitken (Jack Aitken)", value: "AIT" }, // test/reserve driver
];
